services:
  - type: web
    name: dormitory-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0